[package]
name = 'schedule'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'schedule'

[dependencies]
chrono = "0.4.31"
crypto-hash = "0.3.4"
extendr-api = '*'
home = "0.5.5"
rusqlite = "0.29.0"
