# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_schedule_wrappers", use_symbols = TRUE, package_name = "schedule")

#' @docType package
#' @usage NULL
#' @useDynLib schedule, .registration = TRUE
NULL

#' Add a task
#' @export
add_task <- function(time, command, schedule_type) .Call(wrap__add_task, time, command, schedule_type)

#' Remove a task
#' @export
remove_task <- function(task_id) .Call(wrap__remove_task, task_id)

#' List scheduled tasks
#' @export
list_tasks <- function() .Call(wrap__list_tasks)

#' Activate a scheduling queue
#' @export
scheduler <- function() .Call(wrap__scheduler)


