# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_schedule_wrappers", use_symbols = TRUE, package_name = "schedule")

#' @docType package
#' @usage NULL
#' @useDynLib schedule, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

add_task <- function() .Call(wrap__add_task)


# nolint end
